language: erlang
otp_release:
  - 22.0
before_install: set -e
after_script: set +e
script:
  - rebar3 eunit --cover
  - rebar3 cover --verbose
  - rebar3 as test coveralls send
deploy:
  provider: script
  script: rebar3 hex publish --repo hexpm --yes
  skip_cleanup: true
  on:
    tags: true
